### ISSUE TITLE
clarification on LavaMoat/SNOW informationals in console

### ISSUE THREAD

**Issue by Woodpile37** [MetaMask/eth-phishing-detect#11900]
https://metamask.github.io/phishing-warning/v1.2.1/metamask-fox.svg
I'm asking for some clarification on all this through out my browser code I run into this URL https://metamask.github.io/phishing-warning/v1.2.1 on my browser console. I've had so many problems with Metamask. constant problems and im missing 70 percent of my data. basically I cant do anything. Yes I have talked to metamask multiple times. one time the support help person told me he was able to see all my transactions never received clarity on that that. another time I was told to be patient and they would get back to me at the end of the week. nothing was ever fixed and the third time my problem was escalated to a group of your head developers and not only was I pushed aside not once did I receive any clarification on what's going on or how I could fix it. these our just a few issues i see pop up 
Removing intrinsics.Object.hasOwn
Removing intrinsics.%ArrayPrototype%.findLast
Removing intrinsics.%ArrayPrototype%.findLastIndex
Removing intrinsics.%ArrayPrototype%.toReversed
Removing intrinsics.%ArrayPrototype%.toSorted
Removing intrinsics.%ArrayPrototype%.toSpliced
Removing intrinsics.%ArrayPrototype%.with
Removing intrinsics.%ArrayPrototype%.@@unscopables.findLast
Removing intrinsics.%ArrayPrototype%.@@unscopables.findLastIndex
Removing intrinsics.%ArrayPrototype%.@@unscopables.toReversed
Removing intrinsics.%ArrayPrototype%.@@unscopables.toSorted
Removing intrinsics.%ArrayPrototype%.@@unscopables.toSpliced
Removing intrinsics.%ArrayBufferPrototype%.maxByteLength
Removing intrinsics.%ArrayBufferPrototype%.resizable
Removing intrinsics.%ArrayBufferPrototype%.resize
Removing intrinsics.%StringPrototype%.at
Removing intrinsics.%StringPrototype%.isWellFormed
Removing intrinsics.%StringPrototype%.toWellFormed
Removing intrinsics.%TypedArrayPrototype%.findLast
metamask.github.io/phishing-warning/v1.2.1/lockdown-install.js:1 Removing intrinsics.%TypedArrayPrototype%.findLastIndex
Removing intrinsics.%TypedArrayPrototype%.toReversed
Removing intrinsics.%TypedArrayPrototype%.toSorted
Removing intrinsics.%TypedArrayPrototype%.with
and it points to this URL 
metamask.github.io/phishing-warning/v1.2.1/bundle.js:17
missing dep: ethjs>ethjs-unit>bn.js requested buffer
missing dep: ethjs>number-to-bn>bn.js requested buffer
missing dep: ethjs-contract>ethjs-abi>bn.js requested buffer
missing dep: ethjs>bn.js requested buffer
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 "networkDidChange" listeners added. Use emitter.setMaxListeners() to increase limit.
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 14 "update" listeners added. Use emitter.setMaxListeners() to increase limit.

**Comment by verybigelephants** [comment]
![image](https://github.com/MetaMask/eth-phishing-detect/assets/3118985/b1fc2a5f-610c-4de7-bef7-cbe1133c7535)
Chrome 114.0.5735.110 (Official Build) (64-bit) (cohort: Stable) 
10th of June, 2023

**Comment by appurist** [comment]
For any users that report this as an issue, I have just told them to uninstall the MetaMask extension. 

I've love to be able to tell them how to _disable_ these warnings, instead of disabling or removing the whole extension. The sites in question don't even use MetaMask.

**Comment by Woodpile37** [comment]
I would like to know how to fix this issue

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by verybigelephants** [comment]
> For any users that report this as an issue, I have just told them to uninstall the MetaMask extension.
> 
> I'd love to be able to tell them how to _disable_ these warnings, instead of disabling or removing the whole extension. The sites in question don't even use MetaMask.

This is not about a "webpage" using metamask, since you're including metamask in your extension that is always present in the taskbar, you will always get this error.

And this is something that metamask should fix, as this is their code generate developer warnings in their code 
```
                        !1 !== subPermit && console.warn(`Removing ${subPath}`);
```

and we should absolutely not get some extension's developer warnings in production mode ffs

**Comment by AlexHerman1** [comment]
Hi,

I will reopen this issue. Sorry about the confusion!

**Comment by appurist** [comment]
@AlexHerman1 Thanks! I really appreciate seeing it reopened and assigned!

**Comment by Woodpile37** [comment]
my browser console warnings/errors


SNOW INTERCEPTED NEW WINDOW CREATION IN METAMASK APP:  Window null
16:23:08.286 use-snow.js:6 SNOW INTERCEPTED NEW WINDOW CREATION IN METAMASK APP:  Window null
16:23:08.306  Setting up Sentry Remote Error Reporting for 'production-flask': SENTRY_DSN
16:23:08.408   Removing intrinsics.JSON.rawJSON 
16:23:08.410   Removing intrinsics.JSON.isRawJSON 
16:23:08.413   Removing intrinsics.%ArrayPrototype%.toReversed
16:23:08.414   Removing intrinsics.%ArrayPrototype%.toSorted 
16:23:08.415   Removing intrinsics.%ArrayPrototype%.toSpliced
16:23:08.415   Removing intrinsics.%ArrayPrototype%.with 
16:23:08.417   Removing intrinsics.%ArrayPrototype%.@@unscopables.toReversed 
16:23:08.418   Removing intrinsics.%ArrayPrototype%.@@unscopables.toSorted
16:23:08.419   Removing intrinsics.%ArrayPrototype%.@@unscopables.toSpliced
16:23:08.420   Removing intrinsics.%ArrayBufferPrototype%.transferToFixedLength 
16:23:08.422   Removing intrinsics.%ArrayBufferPrototype%.detached 
16:23:08.424   Removing intrinsics.%StringPrototype%.isWellFormed 
16:23:08.425   Removing intrinsics.%StringPrototype%.toWellFormed
16:23:08.426   Removing intrinsics.%RegExpPrototype%.unicodeSets 
16:23:08.427   Removing intrinsics.%FunctionPrototype%.apply.prototype 
16:23:08.427   Tolerating undeletable intrinsics.%FunctionPrototype%.apply.prototype === undefined 
16:23:08.429   Removing intrinsics.%FunctionPrototype%.bind.prototype
16:23:08.430   Tolerating undeletable intrinsics.%FunctionPrototype%.bind.prototype === undefined 
16:23:08.432   Removing intrinsics.%TypedArrayPrototype%.toReversed 
16:23:08.434   Removing intrinsics.%TypedArrayPrototype%.toSorted
16:23:08.437   Removing intrinsics.%TypedArrayPrototype%.with
16:23:08.536   Property eval will not be hardened because it is scuttled by LavaMoat protection. Visit https://github.com/LavaMoat/LavaMoat/pull/360 to learn more.
16:23:08.873   missing dep: ethjs>ethjs-unit>bn.js requested buffer
16:23:08.882   missing dep: ethjs>number-to-bn>bn.js requested buffer 
16:23:08.968  WARNING: Missing strong random number source
16:23:09.151   missing dep: ethjs-contract>ethjs-abi>bn.js requested buffer
16:23:09.635   MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 "update" listeners added. Use emitter.setMaxListeners() to increase limit.
16:23:09.637   MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 14 "update" listeners added. Use emitter.setMaxListeners() to increase limit.
16:23:09.648 use-snow.js:6 SNOW INTERCEPTED NEW WINDOW CREATION IN METAMASK APP:  global <iframe src=​"https:​/​/​metamask.github.io/​phishing-warning/​v2.1.0/​#extensionStartup" sandbox=​"allow-scripts allow-same-origin">​…​</iframe>​
17:08:35.577   MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 "update" listeners added. Use emitter.setMaxListeners() to increase limit.

**Comment by wottpal** [comment]
Same issue. Great to see this one tackled 👍

**Comment by amirulfaiz98** [comment]
Same here, got the same issue, just wandering for a few days why my project can't connect with metamask

**Comment by 409H** [comment]
This is not an issue specific with MetaMask/eth-phishing-detect. It does seem to be logging informationals to the console wrt to snow/lavamoat - which isn't a big deal.

cc: @weizman

**Comment by weizman** [comment]
Snow messages are perfectly fine. Not only that, but most of the messages above are lavamoat related, not snow. And either way, they're all legit, they don't indicate any problematic errors, just some warnings. 
What seems to bother everyone exactly?

**Comment by appurist** [comment]
@409H It's the `Removing intrinsics` messages that are the problem. See [the first comment](https://github.com/MetaMask/eth-phishing-detect/issues/11900#issuecomment-1585744021) from @verybigelephants for the unwanted warnings. As far as I know, these are definitely coming from the Metamask plugin.  (And disabling it resolves the problem, but is undesireable.)

**Comment by appurist** [comment]
@weizman "Removing intrinsics" is the only MM issue. See [this StackOverflow](https://stackoverflow.com/a/76393381/3029882) too.

**Comment by mxismean** [comment]
same issue

**Comment by Jude3332** [comment]
same issue here .

**Comment by copostic** [comment]
Same here?

**Comment by k3srpn** [comment]
Same here

**Comment by DigiCris** [comment]
Is there any update on this? I don't think I'll be moving away from metamask but it is annoying.

**Comment by community0x** [comment]
Same problem here, any update?

**Comment by weizman** [comment]
https://github.com/MetaMask/metamask-extension/pull/19754 is merged, you should see this problem is fixed in the next release. Feel free to tag me and reopen this issue ONLY if this doesn't solve the problem :)

**Comment by Yanykberesh** [comment]
I had such a problem, I was contacted by a fraudster who wanted to "help" me, fix some metamask errors so that transactions do not fail, we contacted him, I turned on the screen demonstration, he told me to show him the code of the metamask page and expand these errors, after which he hacked my wallet, I didn't believe him but he sent me my address and private and public key in chat, how is it possible? I managed to send assets to other wallets, but in my opinion it is quite a global problem if a wallet can be stolen so easily

**Comment by Livedollar** [comment]
I have the same problem but I am completely unable to use metamask . I press connect button on a multisig and it has that yellow spin thing that freezes, turn off the extension, turn on, same thing. Freeze I switched from infura rpc and was able to use it for a bit so I switched back,  I was coding and began having problems with css and noticed the 17 warnings and some errors.
 I was hoping for a solution, my funds are kind of important to me .
  A few other people in our DAO began experiencing the wallet just locking up when signing and these errors in the console. 
 Is there a way to batch transfer all  tokens out of MetaMask wallet ?

**Comment by wottpal** [comment]
This still is an issue in the latest Metamask extension version (at least for me). When will this PR be part of a release, @weizman? 🤔

**Comment by appurist** [comment]
@wottpal I still see the problem with 10.33.1 but it seems to be resolved in 10.34.0 (released July 17, 2023 in the Chrome store).

**Comment by rluna319** [comment]
Issue is resolved on my end after updating to 10.34.0

**Comment by aScHEABL** [comment]
As of 9/30/2023 this issue is not resolved.

**Comment by wizardlabsxyz** [comment]
I'm seeing this in V11 of Metamask on Chrome

**Comment by aScHEABL** [comment]
@weizman This issue is still not resolved in the latest version of metamask. In case you didn't see it.

**Comment by appurist** [comment]
This _was_ resolved in 10.34.0 (released July 17, 2023 in the Chrome store) but perhaps there's a regression problem in 11.x, lost the fix?

**Comment by aScHEABL** [comment]
@weizman This issue is still not fixed, did you receive the notification? It's been weeks.

**Comment by cryptodigi** [comment]
issue still present on ver 11.11.0

**Comment by LakshmiSanikommu** [comment]
@weizman , issue is still there , i was seeking those logs

**Comment by Michael679089** [comment]
issue still persists.

<img width="932" height="632" alt="Image" src="https://github.com/user-attachments/assets/875ac7b0-6625-45ef-a02b-e27426d68d30" />

firefox version, maybe latest, I just downloaded from firefox extension.
Hold on let me see. It says these:

Author
[danfinlay](https://addons.mozilla.org/en-US/firefox/user/12436990/?utm_source=firefox-browser&utm_medium=firefox-browser&utm_content=addons-manager-user-profile-link)
Version
13.11.2
Last Updated
January 26, 2026
Rating
[1,091 reviews](https://addons.mozilla.org/en-US/firefox/addon/ether-metamask/reviews/?utm_source=firefox-browser&utm_medium=firefox-browser&utm_content=addons-manager-reviews-link)

**Comment by zedd3v** [comment]
Still getting this
