### ISSUE TITLE
blocklist removal

### ISSUE THREAD

**Issue by tanmoy119** [MetaMask/eth-phishing-detect#179229]
![Image](https://github.com/user-attachments/assets/d509072e-b8e9-4d75-aeb2-8ca595cb5267)

**Comment by tanmoy119** [comment]
Inside metamask app browser  when I am visiting my website (travls.io) and trying to connect my metamask  wallet this window is coming .

**Comment by tanmoy119** [comment]
this is my website url -->> https://www.travls.io/

**Comment by AlexHerman1** [comment]
hi, that's strange. let me look into this.

**Comment by tanmoy119** [comment]
hi, is there any update regarding this ?

**Comment by AlexHerman1** [comment]
are you still experiencing the block?

**Comment by tanmoy119** [comment]
this window is coming .

**Comment by tanmoy119** [comment]
![Image](https://github.com/user-attachments/assets/67fc8efa-07b1-40ba-9efd-b8ca9821cef0)

**Comment by AlexHerman1** [comment]
okay, reverting internally on this

**Comment by tanmoy119** [comment]
hi, is there any update ?

**Comment by AlexHerman1** [comment]
were working on it. are you still experiencing the block?

**Comment by tanmoy119** [comment]
ya , when ever I am trying to connect my wallet "This website might be harmful" warning is coming .

**Comment by AlexHerman1** [comment]
okay. we are having an issue that is in the process of being diagnosed. thanks for your patience on this.

**Comment by itripleg** [comment]
I'm having this issue as well - which I didn't have prior to 13.0.1

**Comment by tanmoy119** [comment]
hi , is there any update on that issue please let me know .

**Comment by AlexHerman1** [comment]
this should be fixed now pls let me know.

**Comment by tanmoy119** [comment]
please check your self , from your end once  because that "This website might be harmful" issue is still there .

**Comment by AlexHerman1** [comment]
im unable to reproduce this on my end. please clarify

**Comment by tanmoy119** [comment]
thank you for your concern and support, The issue fixed now .
