### ISSUE TITLE
Blocklist removal request

### ISSUE THREAD

**Issue by ssebassv** [MetaMask/eth-phishing-detect#182940]
### Legitimate domains, IPs, IPFS hashes, or IPNS names

https://www.fortunemaster.io

### Website Information

**Domain:** www.fortunemaster.io

**Project:** Fortune Master

**Category:** Web3 Prize Draws & Loyalty Program

**Blockchain:** Arbitrum, BSC, Polygon

### Project Description

Fortune Master is a legitimate Web3 project focused on community-based prize draws, reward NFT collections, and a loyalty rewards program (Fortune Gems).

- Users participate by purchasing Draw NFTs to enter our prize draws. 
- Community members can also earn rewards through our Ambassador Program and The Fortune Club (loyalty program). 
- Fortune Gems are distributed as a free loyalty token, not sold through ICOs or paywalls. 

We are a transparent project with an active community and clear documentation.

### Website Functionality

Our website is our:
- Official project hub for Fortune Master.
- Information center for prize draws, reward NFTs, and loyalty program.
- Connection point for our community (Discord, Telegram, X/Twitter).
- Let's our community interact with our smart contract.

### Why This Is a False Positive

- **No phishing or malicious intent:** The website does not request private keys, seed phrases, or sensitive login data.
- **No impersonation:** We do not impersonate MetaMask, any wallet, or any other project.
- **No** false **promises:** We do not advertise “guaranteed profits” or “risk-free” schemes.
- **Transparency:** All token and NFT information is explained clearly and backed by smart contracts.

### Actual Legitimacy

- We have an active community on Discord, Telegram, and X/Twitter.
- Transparent roadmap and Terms & Conditions.
- Fortune Gems are positioned clearly as a loyalty reward token, not an investment.
- We don't do deceptive or scam practices.

### Request for Whitelist Approval

Our website, FortuneMaster.io, is a legitimate cryptocurrency prize draw and loyalty project website. It poses no security threat to users and should not be classified as phishing.

We kindly request that it be removed from the blocklist and added to the allowlist.

Thank you in advance for your review.

### Is this a duplicate request?

- [x] I have checked the issues page and confirmed this is not a duplicate request

**Comment by ssebassv** [comment]
![Image](https://github.com/user-attachments/assets/d6df8475-49fc-47cb-b7d4-31f8b567d240)

**Comment by AlexHerman1** [comment]
hi, this site seems pretty suspect. can you clarify what this project really is?

**Comment by ssebassv** [comment]
Sure. So, our project is a blockchain-based prize draw. Our participants buy NFTs, which act as entries into the draw, and all sales go into a prize pool. Once all NFTs for a draw are sold, the smart contract uses ChainLink VRF to fairly select 3 winners. The prizes are then distributed automatically to those 3 winners.

We currently run draws on Arbitrum, BSC, and Polygon. Everything is handled on-chain, and users never need to provide private keys or sensitive information. Our site only serves as an interface for interacting with our contracts.

**Comment by AlexHerman1** [comment]
this has been fixed, thanks for the report

**Comment by AlexHerman1** [comment]
@ssebassv  are you still experiencing this issue

**Comment by ssebassv** [comment]
Hi @AlexHerman1 
Yes, it keeps appearing. I tried last night and this morning, and the message still appears. I even deleted the app and reinstalled it before checking, and the message persists.

![Image](https://github.com/user-attachments/assets/ae133b09-2ea1-413c-a911-6799e2df9348)
![Image](https://github.com/user-attachments/assets/5397b3d9-ccf1-4a21-8ba4-3a328ff6829f)
