### ISSUE TITLE
Blocklist removal request

### ISSUE THREAD

**Issue by mobilonnapp** [MetaMask/eth-phishing-detect#187533]
### Legitimate domains, IPs, IPFS hashes, or IPNS names

Hello MetaMask team,

Our project website https://dexverse.io/ has been mistakenly flagged as a malicious/phishing site.

**Project Name:** Dexverse

**Website:** https://dexverse.io/

**Socials:**

Twitter: https://x.com/Dexverse_io

Telegram: https://t.me/dexversenews

Instagram: https://instagram.com/dexverse_io

We confirm that our domain is legitimate, secured with SSL, and does not host any phishing or malicious activity.
It seems to have been flagged in error.

**Could you please review and remove our domain from the blocklist?**

Thank you for your support.

Best regards,
Dexverse Team

### Please explain why this content is legitimate

Secure domain and SSL: Our website https://dexverse.io/
 uses HTTPS with a valid SSL certificate, ensuring secure communication between users and our servers.

Transparent project information: We provide clear and verifiable information about our project, team, and social channels:

Twitter: https://x.com/Dexverse_io

Telegram: https://t.me/dexversenews

Instagram: https://instagram.com/dexverse_io

No phishing or malicious activity: Our site does not ask users for private keys, seed phrases, or personal information unrelated to Web3 connectivity. We only interact with wallets via standard Web3 connection methods (e.g., MetaMask connect).

Reputation in the Web3 community: Dexverse is an active and transparent project with a social media presence and community engagement. We have not been reported for scams or fraud.

Clear purpose: Our website provides legitimate Web3 services and information; it does not impersonate other projects or attempt to steal user assets.

### Is this a duplicate request?

- [x] I have checked the issues page and confirmed this is not a duplicate request

**Comment by AlexHerman1** [comment]
this should be resolved now. please give the change an hour or two to propagate.

**Comment by mobilonnapp** [comment]
The issue still persists after one day. Please check the screenshot. 

![Image](https://github.com/user-attachments/assets/bf7b09df-a971-45e1-bab2-d858e2f57672)
