### ISSUE TITLE
Blocklist removal request

### ISSUE THREAD

**Issue by aydbasak** [MetaMask/eth-phishing-detect#188423]
### Legitimate domains, IPs, IPFS hashes, or IPNS names

https://stake.bellatorlife.com/
https://bellatorlife.com/

### Please explain why this content is legitimate

Hello,

The domains bellatorlife.com and stake.bellatorlife.com are legitimate websites and are not related to phishing or scam activities.

Please remove them from the blocklist.

Thank you.

### Is this a duplicate request?

- [x] I have checked the issues page and confirmed this is not a duplicate request

**Comment by AlexHerman1** [comment]
this has been resolved, please allow 30 mins to an hour for changes to propagate.

**Comment by aydbasak** [comment]
Hello,

Thank you for your support on this matter. We noticed that this issue was marked as resolved 4 days ago, but the domains bellatorlife.com and stake.bellatorlife.com still appear to be blocked in MetaMask.

Would you kindly check once again if the changes have been fully propagated, or advise us if there are any further steps we should take on our side?

We truly appreciate your assistance.

Best regards,
