### ISSUE TITLE
Metamask website blacklist.

### ISSUE THREAD

**Issue by usamasarwar1** [MetaMask/eth-phishing-detect#188409]
Hi, 

My website: https://www.amfi.ai/ is blacklisted on metamask though we are not doing any spam or fake work. Please whitelist my website and let me know if there are any suggestions for me. 

Thanks!

**Comment by AlexHerman1** [comment]
hi, this should be fixed. please allow up to an hour for changes to propagate.

**Comment by usamasarwar1** [comment]
Hi Alex, 

I am still getting the same message when I open https://www.amfi.ai/ inside Metamask mobile app.
