### ISSUE TITLE
[Legitimate Site Blocked] clovis.network

### ISSUE THREAD

**Issue by yei-admin** [MetaMask/eth-phishing-detect#190666]
### Legitimate domains, IPs, IPFS hashes, or IPNS names

https://vault.clovis.network
https://www.clovis.network

### Is this a duplicate request?

- [x] I have checked the issues page and confirmed this is not a duplicate request

**Comment by AlexHerman1** [comment]
this should be fixed within an hour or two.

**Comment by yei-admin** [comment]
Hey @AlexHerman1 

we’re still encountering the MetaMask malicious site warning when attempting to connect a wallet on the domains mentioned above. Could you please help check and resolve this issue? Thanks!

<img width="400" height="532" alt="Image" src="https://github.com/user-attachments/assets/b1287012-46a5-413d-a01c-49b7112cbb37" />
