### ISSUE TITLE
Blocklist removal request - www.myra.fun

### ISSUE THREAD

**Issue by rekpero** [MetaMask/eth-phishing-detect#195311]
### Legitimate domains, IPs, IPFS hashes, or IPNS names

https://www.myra.fun
htttps://myra.fun

### Please explain why this content is legitimate

I’m facing an issue where my application domain is being incorrectly flagged as **"Malicious Site"** when users try to connect via MetaMask.

🧩 Issue Summary
- When authenticating to the dApp using MetaMask via signature, users are shown a “review alert” or a warning indicating the app is malicious.
- The domain is newly purchased and had no previous activity or history before being used for this project.
- The site itself is not blocked and loads fine in any browser, the issue only occurs at the MetaMask connection step.
- This warning is causing user onboarding friction, damaging trust and credibility for our application.

How to fix this issue? can you add it to allowlist so that this alert is removed?

<img width="400" height="532" alt="Image" src="https://github.com/user-attachments/assets/50ab4d57-f5dd-4544-8197-32e8ae32294b" />

### Is this a duplicate request?

- [x] I have checked the issues page and confirmed this is not a duplicate request

**Comment by AlexHerman1** [comment]
this should be fixed. please allow a few hours for the fix to propagate.

**Comment by rekpero** [comment]
<img width="922" height="326" alt="Image" src="https://github.com/user-attachments/assets/35afbf72-d81a-4c89-8ee0-1df542bba870" />

Hey @AlexHerman1 i'm still getting the malicious site for our app on metamask. how to resolve this?
