### ISSUE TITLE
Blocklist removal request

### ISSUE THREAD

**Issue by DucChanHUST** [MetaMask/eth-phishing-detect#195657]
### Legitimate domains, IPs, IPFS hashes, or IPNS names

App: https://app.tcvault.xyz
X: https://x.com/tcv_platform

### Please explain why this content is legitimate

I would like to request a review and removal of the current scam/phishing warning on our dApp. Our project is legitimate, and the existing label appears to be a false positive. We believe the warning may stem from a misunderstanding, as our application operates transparently and does not perform any malicious actions.

- Our smart contracts are audited by Trufy: https://trufy.io/reports/index.html . They do not contain any backdoors, hidden fees, or withdrawal functions that compromise user funds.

- We do not request or collect private keys, seed phrases, or any sensitive user credentials.

- The dApp only interacts with the user’s wallet through standard, permissioned contract calls, and users maintain full control over their assets at all times.

- Our website and infrastructure do not engage in phishing, misleading UI behavior, or unauthorized transactions.

### Is this a duplicate request?

- [x] I have checked the issues page and confirmed this is not a duplicate request

**Comment by AlexHerman1** [comment]
this should be fixed, please allow an hour or two for the changes to propagate.

**Comment by DucChanHUST** [comment]
> this should be fixed, please allow an hour or two for the changes to propagate.

<img width="401" height="660" alt="Image" src="https://github.com/user-attachments/assets/5813e374-b4ea-41af-a597-c27b675a4c44" />

It hasn't changed anything yet, it still shows warning even when I withdraw
