### ISSUE TITLE
[Legitimate Site Blocked] pepenode.io

### ISSUE THREAD

**Issue by pepenodegh** [MetaMask/eth-phishing-detect#196913]
### Legitimate domains, IPs, IPFS hashes, or IPNS names

https://pepenode.io

### Please explain why this content is legitimate

Our legitimate website, [pepenode.io](https://pepenode.io), appears to have been incorrectly blocked. This is an active and legitimate project with audits available directly on our website.
Official X Account: https://x.com/pepenode_io
We request immediate action to unblock our site. Please let us know if you require any further information to expedite this process.

Thank you for your attention to this urgent matter.

### Is this a duplicate request?

- [x] I have checked the issues page and confirmed this is not a duplicate request

**Comment by pepenodegh** [comment]
@AlexHerman1

**Comment by AlexHerman1** [comment]
Hi,

This should be resolved now. Please allow a few hours for the change to propagate.

**Comment by pepenodegh** [comment]
@AlexHerman1 this is not resolved all of our customers still getting the same warning, please remove the false block asap

**Comment by pepenodegh** [comment]
@AlexHerman1
