### ISSUE TITLE
domain flagged

### ISSUE THREAD

**Issue by ianternio** [MetaMask/eth-phishing-detect#4045]
Hello,

The domain crypto.co is incorrectly showing a meta mask "phishing" flag.  Can you please investigate?

**Comment by danfinlay** [comment]
Fixed.

**Comment by ianternio** [comment]
Dan - I’m still seeing the flag.  See attached from this morning.

Ian Kane
COO & Founder • TERNIO
ian@ternio.io <mailto:ian@ternio.io> • (704) 218-9335




On Sep 29, 2020, at 7:31 PM, Dan Finlay <notifications@github.com> wrote:


Fixed.

**Comment by ianternio** [comment]
It’s all good now!  Thank you.

Ian Kane
COO & Founder • TERNIO
ian@ternio.io <mailto:ian@ternio.io> • (704) 218-9335





On Sep 30, 2020, at 9:16 AM, Ian Kane <ian@ternio.io> wrote:

Dan - I’m still seeing the flag.  See attached from this morning.

Ian Kane
COO & Founder • TERNIO
ian@ternio.io <mailto:ian@ternio.io> • (704) 218-9335

<Screen Shot 2020-09-30 at 9.08.37 AM.png>



On Sep 29, 2020, at 7:31 PM, Dan Finlay <notifications@github.com <mailto:notifications@github.com>> wrote:


Fixed.
