### ISSUE TITLE
Site incorrectly put on phishing list

### ISSUE THREAD

**Issue by Renato-C** [MetaMask/eth-phishing-detect#4342]
Hi, a part of my domain (tegger.io) is being blocked for metamask users. We do not offer, accept, exchange or otherwise use any crypto on our site. Our site uses "tokens" (points in our internal accounting) to reward users and then lets them exchange them on our marketplace. However, these points are not cryptos and cannot be sent out of our system.

This is the part of my domain that is being blocked: https://tegger.io/marketplace/

Can you please help me whitelist us?

renato@tegger.io

**Comment by Tectract** [comment]
Did you ever get this resolved? Is the metamask team responding to these issues at all? this is very irresponsible of the Metamask team, to falsely accuse all these crypto startups of being "phishing" domains!

**Comment by Renato-C** [comment]
No response or resolution sadly...

**Comment by danfinlay** [comment]
Very sorry, Fixed by #4388

**Comment by Renato-C** [comment]
Thanks for your help Dan. It still appears as blacklisted on my browser, despite deleting cookies, local, and application storage. I'll give some hours in case it needs to replicate through your servers or so and report back if we still see the issue.
