### ISSUE TITLE
Pankcake Swap error

### ISSUE THREAD

**Issue by philochs420** [MetaMask/eth-phishing-detect#4787]
Hi, I'm getting a warning for using pancake swap on the binance smart chain with my mm wallet, pancake swap is a safe site, it's part of the Binance Smart Chain..

**Comment by goldnutter** [comment]
Not an error. They were DNS hijacked to a fake site some time yesterday

DO NOT ENTER YOUR SEED PHRASE ON A SITE 

EVER

**Comment by ethene** [comment]
@goldnutter so it has been fixed now, isn't it?

**Comment by cylim** [comment]
https://dnschecker.org/#NS/pancakeswap.finance
It is not fully resolved yet. Some is still pointing to problematic DNS.

**Comment by ethene** [comment]
https://twitter.com/PancakeSwap/status/1371866176238718984

**Comment by 409H** [comment]
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4803
