### ISSUE TITLE
Update names to "main," "blocklist," and "allowlist."

### ISSUE THREAD

**Issue by LuckyLuker** [MetaMask/eth-phishing-detect#9378]
We want to push using `allowlist`, `blocklist`, and `main` branch terminology over `whitelist`, `blacklist`, and `master` branch.

From @Gudahtt: "We can migrate our config in eth-phishing-detect and change the main branch name from master to main, leaving the old master branch up with the deprecated config format to avoid breakages. We can even write GitHub actions to keep the old config up-to-date for some transition period, or indefinitely"

From @409H:  f we change branch to `main` we will need to let codefi know so they can fetch from `main` instead of `master`

I see this code being used in at least 13 places: https://gitlab.com/search?group_id=7907658&scope=blobs&search=eth-phishing-detect Mainly Metafi and Activate use it.

I am notifying codefi about this issue and will post the slack link in a comment below.

**Comment by LuckyLuker** [comment]
Codefi notified in slack: https://consensys.slack.com/archives/GTVGXR6P4/p1668109652473469

**Comment by 409H** [comment]
Done :D

**Comment by AlexHerman1** [comment]
i think the aliases still appear as the old name schema in the config file? @409H @LuckyLuker

**Comment by legobeat** [comment]
There are some pieces on backwards-compatibility here, both currently (main/master) and upcoming (allowlist/whitelist, blocklist/blacklist)

TODO:

[ ] Ensure users of MetaMask versions prior to 2022-11 use the correct and updated list
  *Previous versions will load from `master` which currently must be done regularly and manually until automatic syncing is in place. [Example](https://github.com/MetaMask/eth-phishing-detect/pull/11633)*
[ ] Update [clients](https://github.com/MetaMask/core/blob/main/packages/phishing-controller/src/PhishingController.ts) to read from both new and old field names (`allowlist` as well as `whitelist`)
[ ] Update schema to use new names (`allowlist` instead of `whitelist`) in public-facing API
[ ] Decide on and announce deprecation timeline
  *(how old metamask versions should still be able to get benefits of phishing detection?)*
[ ] Once deprecated: Complete deprecation of old field names by removing them

The sooner clients are forwards-compatible, the sooner we can consider deprecating the legacy names.

**Comment by 12pfm6** [comment]
can our coin return that they stole?

**Comment by samczsun** [comment]
Closing this since things have probably migrated by now and we're no longer syncing with `master` anymore.
